server:
  port: 8084
spring:
  application:
    name: happy-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.137.135
    username: cai
    password: 123
    virtual-host: /
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期