server:
  port: 10010
spring:
  application:
    name: happy-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**   #路由到商品微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    user-service: /user/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时间5000ms
ribbon:
  ConnectTimeout: 2000 #ribbon链接超时时长
  ReadTimeout: 3500 #读取超时时间
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #当前切换服务次数
